
[ 2024-09-10 14:54:06,051 ] - DEBUG - root - main.py:17 - Initiated Preprocessing Module

[ 2024-09-10 14:54:06,052 ] - DEBUG - root - processDataIngestion.py:11 - Document Ingestion class initialized

[ 2024-09-10 14:54:14,095 ] - DEBUG - root - processDataIngestion.py:33 - Successfully loaded the input file to the memory

[ 2024-09-10 14:54:14,096 ] - DEBUG - root - processEdit.py:10 - Process Edit Message class initialized

[ 2024-09-10 14:54:14,096 ] - DEBUG - root - processJSON.py:25 - JSON Pre-Processing class initiated

[ 2024-09-10 14:54:14,096 ] - DEBUG - root - utils.py:31 - [INFO] : Loading the configuration data

[ 2024-09-10 14:54:14,110 ] - INFO - root - utils.py:37 - Config Yaml loaded succesfully.

[ 2024-09-10 14:54:14,158 ] - DEBUG - root - processEdit.py:85 - Operation on-line extraction has initiated

[ 2024-09-10 14:54:14,159 ] - DEBUG - root - processEdit.py:32 - Started operation on line level adjustment

[ 2024-09-10 14:54:14,160 ] - DEBUG - root - processEdit.py:67 - Forwarding JSON object for futher pre-processing task

[ 2024-09-10 14:54:14,160 ] - DEBUG - root - processJSON.py:386 - Dealing with missing columns and sheets

[ 2024-09-10 14:54:14,185 ] - DEBUG - root - processJSON.py:55 - Started extraction of claim IDs from the input file

[ 2024-09-10 14:54:14,188 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,190 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,205 ] - DEBUG - root - processJSON.py:308 - Working on Hippa Attribute

[ 2024-09-10 14:54:14,214 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,217 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,252 ] - DEBUG - root - processJSON.py:254 - max date replacement task is started

[ 2024-09-10 14:54:14,256 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,258 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,266 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,267 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,375 ] - DEBUG - root - processJSON.py:336 - Dealing with Raw data from COB

[ 2024-09-10 14:54:14,376 ] - DEBUG - root - processJSON.py:254 - max date replacement task is started

[ 2024-09-10 14:54:14,382 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,383 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,439 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,440 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,457 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,459 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,491 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,492 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,534 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,535 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,589 ] - DEBUG - root - processJSON.py:87 - Data persistance is started

[ 2024-09-10 14:54:14,603 ] - INFO - root - processJSON.py:101 - Data JSON is stored at the location : C:\Users\2332220\OneDrive - Cognizant\Desktop\GenAI_24\0_Experimentals\0_Expr_Test\1_EXCEL_JSON\1_Input_PreProcessing\artifacts\output\24B121111110_wm_invalidproviderselection.json

[ 2024-09-10 14:54:14,604 ] - DEBUG - root - processEdit.py:32 - Started operation on line level adjustment

[ 2024-09-10 14:54:14,606 ] - DEBUG - root - processEdit.py:67 - Forwarding JSON object for futher pre-processing task

[ 2024-09-10 14:54:14,607 ] - DEBUG - root - processJSON.py:386 - Dealing with missing columns and sheets

[ 2024-09-10 14:54:14,639 ] - DEBUG - root - processJSON.py:55 - Started extraction of claim IDs from the input file

[ 2024-09-10 14:54:14,644 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,646 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,657 ] - DEBUG - root - processJSON.py:308 - Working on Hippa Attribute

[ 2024-09-10 14:54:14,666 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,668 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,702 ] - DEBUG - root - processJSON.py:254 - max date replacement task is started

[ 2024-09-10 14:54:14,705 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,707 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,717 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,718 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,837 ] - DEBUG - root - processJSON.py:336 - Dealing with Raw data from COB

[ 2024-09-10 14:54:14,838 ] - DEBUG - root - processJSON.py:254 - max date replacement task is started

[ 2024-09-10 14:54:14,843 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,844 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,901 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,902 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,913 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,915 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,947 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:14,948 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:14,999 ] - DEBUG - root - processJSON.py:205 - Data cleaning task is started

[ 2024-09-10 14:54:15,001 ] - DEBUG - root - processJSON.py:117 - Data type conversion task is started

[ 2024-09-10 14:54:15,058 ] - DEBUG - root - processJSON.py:87 - Data persistance is started

[ 2024-09-10 14:54:15,069 ] - INFO - root - processJSON.py:101 - Data JSON is stored at the location : C:\Users\2332220\OneDrive - Cognizant\Desktop\GenAI_24\0_Experimentals\0_Expr_Test\1_EXCEL_JSON\1_Input_PreProcessing\artifacts\output\24B121111110_wm_invalidproviderselectiononline1.json

[ 2024-09-10 14:54:15,071 ] - DEBUG - root - dataFiltration.py:10 - filterData class initialized

[ 2024-09-10 14:54:15,087 ] - DEBUG - root - dataFiltration.py:222 - Got ['24B121111110_wm_invalidproviderselection.json', '24B121111110_wm_invalidproviderselectiononline1.json'] for filtering

[ 2024-09-10 14:54:15,089 ] - DEBUG - root - dataFiltration.py:234 - Started filtering 24B121111110_wm_invalidproviderselection

[ 2024-09-10 14:54:15,089 ] - DEBUG - root - dataFiltration.py:165 - Started filtering and appying 2 filter/s

[ 2024-09-10 14:54:15,114 ] - ERROR - root - main.py:42 - There seems to be a issue in Preprocessing - Traceback (most recent call last):
  File "C:\Users\2332220\OneDrive - Cognizant\Desktop\GenAI_24\0_Experimentals\0_Expr_Test\1_EXCEL_JSON\1_Input_PreProcessing\components\dataFiltration.py", line 110, in convertToDataframe
    if type(inputFile[sheet]) == list: # if sheet data is not empty or not a string
KeyError: 'hippaattributes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2332220\OneDrive - Cognizant\Desktop\GenAI_24\0_Experimentals\0_Expr_Test\1_EXCEL_JSON\1_Input_PreProcessing\components\dataFiltration.py", line 242, in getFilteredInputFile
    dataFrames = self.filterInputFile(inputFile, filters)
  File "C:\Users\2332220\OneDrive - Cognizant\Desktop\GenAI_24\0_Experimentals\0_Expr_Test\1_EXCEL_JSON\1_Input_PreProcessing\components\dataFiltration.py", line 167, in filterInputFile
    dataFrames = self.convertToDataframe(inputFile) # converts dictionary of dataframes
  File "C:\Users\2332220\OneDrive - Cognizant\Desktop\GenAI_24\0_Experimentals\0_Expr_Test\1_EXCEL_JSON\1_Input_PreProcessing\components\dataFiltration.py", line 118, in convertToDataframe
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2332220\OneDrive - Cognizant\Desktop\GenAI_24\0_Experimentals\0_Expr_Test\1_EXCEL_JSON\1_Input_PreProcessing\main.py", line 31, in inputPreprocessUnit
    filterObj.getFilteredInputFile(jsonFileName)
  File "C:\Users\2332220\OneDrive - Cognizant\Desktop\GenAI_24\0_Experimentals\0_Expr_Test\1_EXCEL_JSON\1_Input_PreProcessing\components\dataFiltration.py", line 252, in getFilteredInputFile
    raise Exception()
Exception

